mono GameExecutor.exe 10 0 next &
mono GameExecutor.exe 10 1 next &
mono GameExecutor.exe 10 2 next &
mono GameExecutor.exe 10 3 next &
mono GameExecutor.exe 10 4 next &
mono GameExecutor.exe 10 5 next &
mono GameExecutor.exe 10 6 next &
mono GameExecutor.exe 10 7 next &
mono GameExecutor.exe 10 8 next &
mono GameExecutor.exe 10 9 next &
